/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SlidePuzzleFinal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author erang
 */
public class frame1 extends javax.swing.JFrame {
    
    private Timer timer;
    private String username;
    
    
    
    
    

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
        
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            countme();
            }
        });
        getUsernameFromUser();
        timer.start();
        
            
        
        
            
    
                }
    int i=0;
    public void countme(){
        
        i++;
        jlabelTime.setText(String.valueOf(i));
        
        
               
    }
    public void isOver(){
        
        if(counter>250){
            
            JOptionPane.showMessageDialog(null, "You have exceeded the maximum no of clicks");
            
            
            
        }
        
        
    }
     private void getUsernameFromUser() {
        
        username = JOptionPane.showInputDialog(null, "Enter your username:", "Welcome to Puzzle Game", JOptionPane.PLAIN_MESSAGE);

       
       
        
        jlabelusername.setText(username);
        
    }
   
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum10 = new javax.swing.JButton();
        jbtnNum11 = new javax.swing.JButton();
        jbtnNum12 = new javax.swing.JButton();
        jbtnNum13 = new javax.swing.JButton();
        jbtnNum14 = new javax.swing.JButton();
        jbtnNum15 = new javax.swing.JButton();
        jbtnNum16 = new javax.swing.JButton();
        jbtnSolve = new javax.swing.JButton();
        jbtnQuit = new javax.swing.JButton();
        jlabaleClicksNumber = new javax.swing.JLabel();
        jlabelClicks2 = new javax.swing.JLabel();
        jbtnReset = new javax.swing.JButton();
        jlabelClicks3 = new javax.swing.JLabel();
        jlabelTime = new javax.swing.JLabel();
        jlabelClicks5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabelClicks6 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblMin2 = new javax.swing.JLabel();
        jlblMoves2 = new javax.swing.JLabel();
        jlblMin1 = new javax.swing.JLabel();
        jlblMoves1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlabelClicks7 = new javax.swing.JLabel();
        jlabelusername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("            Slide Puzzle Game");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 100));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));

        jbtnNum1.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum1.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum1.setText("4");
        jbtnNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum1ActionPerformed(evt);
            }
        });

        jbtnNum4.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum4.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum4.setText("15");
        jbtnNum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum4ActionPerformed(evt);
            }
        });

        jbtnNum3.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum3.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum3.setText("5");
        jbtnNum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum3ActionPerformed(evt);
            }
        });

        jbtnNum2.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum2.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum2.setText("13");
        jbtnNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum2ActionPerformed(evt);
            }
        });

        jbtnNum5.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum5.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum5.setText("11");
        jbtnNum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum5ActionPerformed(evt);
            }
        });

        jbtnNum6.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum6.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum6.setText("9");
        jbtnNum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum6ActionPerformed(evt);
            }
        });

        jbtnNum7.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum7.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum7.setText("1");
        jbtnNum7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum7ActionPerformed(evt);
            }
        });

        jbtnNum8.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum8.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum8.setText("7");
        jbtnNum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum8ActionPerformed(evt);
            }
        });

        jbtnNum9.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum9.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum9.setText("12");
        jbtnNum9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum9ActionPerformed(evt);
            }
        });

        jbtnNum10.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum10.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum10.setText("2");
        jbtnNum10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum10ActionPerformed(evt);
            }
        });

        jbtnNum11.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum11.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum11.setText("6");
        jbtnNum11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum11ActionPerformed(evt);
            }
        });

        jbtnNum12.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum12.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum12.setText("13");
        jbtnNum12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum12ActionPerformed(evt);
            }
        });

        jbtnNum13.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum13.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum13ActionPerformed(evt);
            }
        });

        jbtnNum14.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum14.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum14.setText("3");
        jbtnNum14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum14ActionPerformed(evt);
            }
        });

        jbtnNum15.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum15.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum15.setText("8");
        jbtnNum15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum15ActionPerformed(evt);
            }
        });

        jbtnNum16.setBackground(new java.awt.Color(255, 255, 204));
        jbtnNum16.setFont(new java.awt.Font("Felix Titling", 1, 68)); // NOI18N
        jbtnNum16.setText("10");
        jbtnNum16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnNum16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum16ActionPerformed(evt);
            }
        });

        jbtnSolve.setBackground(new java.awt.Color(255, 255, 204));
        jbtnSolve.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N
        jbtnSolve.setText("Solve");
        jbtnSolve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolveActionPerformed(evt);
            }
        });

        jbtnQuit.setBackground(new java.awt.Color(255, 255, 204));
        jbtnQuit.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N
        jbtnQuit.setText("Quit");
        jbtnQuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitActionPerformed(evt);
            }
        });

        jlabaleClicksNumber.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N

        jlabelClicks2.setBackground(new java.awt.Color(255, 255, 204));
        jlabelClicks2.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N
        jlabelClicks2.setText("Moves");

        jbtnReset.setBackground(new java.awt.Color(255, 255, 204));
        jbtnReset.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jlabelClicks3.setBackground(new java.awt.Color(255, 255, 204));
        jlabelClicks3.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jlabelClicks3.setText("time(s):");

        jlabelTime.setBackground(new java.awt.Color(255, 255, 204));
        jlabelTime.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N

        jlabelClicks5.setBackground(new java.awt.Color(255, 255, 204));
        jlabelClicks5.setFont(new java.awt.Font("Felix Titling", 1, 60)); // NOI18N
        jlabelClicks5.setText("/ 250");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jbtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jbtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jbtnNum13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnSolve, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jlabaleClicksNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabelClicks5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jlabelClicks2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlabelClicks3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jlabelClicks2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabaleClicksNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelClicks5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jbtnSolve, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jbtnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNum13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelClicks3)
                    .addComponent(jlabelTime))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 970, 780));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelClicks6.setBackground(new java.awt.Color(255, 255, 204));
        jlabelClicks6.setFont(new java.awt.Font("Felix Titling", 1, 44)); // NOI18N
        jlabelClicks6.setText("Leaderboard");
        jPanel1.add(jlabelClicks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 362, 49));

        lbl2.setBackground(new java.awt.Color(255, 255, 204));
        lbl2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        lbl2.setText("2)");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 54, -1));

        name1.setBackground(new java.awt.Color(255, 255, 204));
        name1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        name1.setText("Player");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel2.setText("Moves");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, 30));

        jlblMin2.setBackground(new java.awt.Color(255, 255, 204));
        jlblMin2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jPanel1.add(jlblMin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, -1));

        jlblMoves2.setBackground(new java.awt.Color(255, 255, 204));
        jlblMoves2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jPanel1.add(jlblMoves2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, 40));

        jlblMin1.setBackground(new java.awt.Color(255, 255, 204));
        jlblMin1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jlblMin1.setText("Player1");
        jPanel1.add(jlblMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, -1));

        jlblMoves1.setBackground(new java.awt.Color(255, 255, 204));
        jlblMoves1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jPanel1.add(jlblMoves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 40));

        lbl3.setBackground(new java.awt.Color(255, 255, 204));
        lbl3.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        lbl3.setText("1)");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 54, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 460, 410));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlabelClicks7.setBackground(new java.awt.Color(0, 153, 153));
        jlabelClicks7.setFont(new java.awt.Font("Felix Titling", 1, 38)); // NOI18N
        jlabelClicks7.setText("Username -");

        jlabelusername.setBackground(new java.awt.Color(255, 255, 204));
        jlabelusername.setFont(new java.awt.Font("Felix Titling", 1, 42)); // NOI18N
        jlabelusername.setText("user");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Game tips\n\n\nPlay untill the maximum no. of moves \nof 250 is exceeded\n\nPlayer who wins with least no. of moves come \nto the top of the leaderboard");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jlabelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabelClicks7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlabelClicks7)
                .addGap(18, 18, 18)
                .addComponent(jlabelusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 450, 370));

        pack();
    }// </editor-fold>                        

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:

        jbtnNum1.setText("7");
        jbtnNum2.setText("3");
        jbtnNum3.setText("15");
        jbtnNum4.setText("13");
        jbtnNum5.setText("1");
        jbtnNum6.setText("");
        jbtnNum7.setText("2");
        jbtnNum8.setText("10");
        jbtnNum9.setText("8");
        jbtnNum10.setText("14");
        jbtnNum11.setText("6");
        jbtnNum12.setText("9");
        jbtnNum13.setText("11");
        jbtnNum14.setText("4");
        jbtnNum15.setText("12");
        jbtnNum16.setText("5");
        jlabaleClicksNumber.setText("");
        counter=0;
        timer.stop();
       jlabelTime.setText("");
       timer.restart();
       
       
        

    }                                         

    private void jbtnQuitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        frame = new JFrame("Quit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure want to quit the game? ", "Puzzle Game", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }

    }                                        

    private void jbtnSolveActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        jbtnNum1.setText("1");
        jbtnNum2.setText("2");
        jbtnNum3.setText("3");
        jbtnNum4.setText("4");
        jbtnNum5.setText("8");
        jbtnNum6.setText("7");
        jbtnNum7.setText("6");
        jbtnNum8.setText("5");
        jbtnNum9.setText("9");
        jbtnNum10.setText("10");
        jbtnNum11.setText("11");
        jbtnNum12.setText("12");
        jbtnNum13.setText("");
        jbtnNum14.setText("15");
        jbtnNum15.setText("14");
        jbtnNum16.setText("13");
        jlabaleClicksNumber.setText("");
        counter=0;
        timer.stop();
        jlabelTime.setText("");
        

    }                                         

    private void jbtnNum16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum16,jbtnNum15);
        EmptySpotChecker(jbtnNum16,jbtnNum12);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum15,jbtnNum11);
        EmptySpotChecker(jbtnNum15,jbtnNum14);
        EmptySpotChecker(jbtnNum15,jbtnNum16);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum14,jbtnNum10);
        EmptySpotChecker(jbtnNum14,jbtnNum13);
        EmptySpotChecker(jbtnNum14,jbtnNum15);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum13,jbtnNum9);
        EmptySpotChecker(jbtnNum13,jbtnNum14);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum12,jbtnNum8);
        EmptySpotChecker(jbtnNum12,jbtnNum11);
        EmptySpotChecker(jbtnNum12,jbtnNum16);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:

        EmptySpotChecker(jbtnNum11,jbtnNum7);
        EmptySpotChecker(jbtnNum11,jbtnNum10);
        EmptySpotChecker(jbtnNum11,jbtnNum12);
        EmptySpotChecker(jbtnNum11,jbtnNum15);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum10,jbtnNum6);
        EmptySpotChecker(jbtnNum10,jbtnNum9);
        EmptySpotChecker(jbtnNum10,jbtnNum11);
        EmptySpotChecker(jbtnNum10,jbtnNum14);
        solutionChecker();
        isOver();
    }                                         

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum9,jbtnNum5);
        EmptySpotChecker(jbtnNum9,jbtnNum10);
        EmptySpotChecker(jbtnNum9,jbtnNum13);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum8,jbtnNum4);
        EmptySpotChecker(jbtnNum8,jbtnNum7);
        EmptySpotChecker(jbtnNum8,jbtnNum12);
        solutionChecker();
        isOver();
        
    }                                        

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        EmptySpotChecker(jbtnNum7,jbtnNum3);
        EmptySpotChecker(jbtnNum7,jbtnNum6);
        EmptySpotChecker(jbtnNum7,jbtnNum8);
        EmptySpotChecker(jbtnNum7,jbtnNum11);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum6,jbtnNum2);
        EmptySpotChecker(jbtnNum6,jbtnNum5);
        EmptySpotChecker(jbtnNum6,jbtnNum7);
        EmptySpotChecker(jbtnNum6,jbtnNum10);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum5,jbtnNum1);
        EmptySpotChecker(jbtnNum5,jbtnNum6);
        EmptySpotChecker(jbtnNum5,jbtnNum9);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum2,jbtnNum1);
        EmptySpotChecker(jbtnNum2,jbtnNum6);
        EmptySpotChecker(jbtnNum2,jbtnNum3);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum3,jbtnNum2);
        EmptySpotChecker(jbtnNum3,jbtnNum4);
        EmptySpotChecker(jbtnNum3,jbtnNum7);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum4,jbtnNum3);
        EmptySpotChecker(jbtnNum4,jbtnNum8);
        solutionChecker();
        isOver();
    }                                        

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EmptySpotChecker(jbtnNum1,jbtnNum2);
        EmptySpotChecker(jbtnNum1,jbtnNum5);
        solutionChecker();
        isOver();
    }                                        

    
    
     int counter;
    void EmptySpotChecker(JButton butt1,JButton butt2){
        String shuffleNumber = butt2.getText();
        if(shuffleNumber == "")
        {
            butt2.setText(butt1.getText());
            butt1.setText("");
            
        }
        
    }
    
    public void solutionChecker(){
        String b1 = jbtnNum1.getText();
        String b2 = jbtnNum2.getText();
        String b3 = jbtnNum3.getText();
        String b4 = jbtnNum4.getText();
        String b5 = jbtnNum5.getText();
        String b6 = jbtnNum6.getText();
        String b7 = jbtnNum7.getText();
        String b8 = jbtnNum8.getText();
        String b9 = jbtnNum9.getText();
        String b10 = jbtnNum10.getText();
        String b11= jbtnNum11.getText();
        String b12 = jbtnNum12.getText();
        String b13= jbtnNum14.getText();
        String b14 = jbtnNum15.getText();
        String b15 = jbtnNum16.getText();
        
        
        if(b1=="1" && b2=="2" && b3=="3" && b4=="4" && b5=="8" && b6=="7" && b7=="6" && b8=="5" && b9=="9" && b10=="10" &&
                b11=="11" && b12=="12" && b13=="15" && b14=="14" && b15=="13"){
            
            
            JOptionPane.showMessageDialog(this, "You have Won the Game");
            
            recordWinners();
             username = JOptionPane.showInputDialog(null, "Enter your username:", "Welcome to Puzzle Game", JOptionPane.PLAIN_MESSAGE);
            jlabelusername.setText(username);
            
             jbtnNum1.setText("7");
        jbtnNum2.setText("5");
        jbtnNum3.setText("6");
        jbtnNum4.setText("13");
        jbtnNum5.setText("1");
        jbtnNum6.setText("");
        jbtnNum7.setText("2");
        jbtnNum8.setText("10");
        jbtnNum9.setText("8");
        jbtnNum10.setText("11");
        jbtnNum11.setText("15");
        jbtnNum12.setText("9");
        jbtnNum13.setText("14");
        jbtnNum14.setText("4");
        jbtnNum15.setText("12");
        jbtnNum16.setText("3");
            counter = 0;
            timer.start();
            
            
            
            
            
            
            
            
        }
        counter++;
        jlabaleClicksNumber.setText(Integer.toString(counter));
        
        
        
        
       
    }
    public  void recordWinners(){
        
       jlblMin1.setText(username);
       jlblMoves1.setText(Integer.toString(counter));
         
        
    }
    
    
    
    
    
    
    
    
    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum10;
    private javax.swing.JButton jbtnNum11;
    private javax.swing.JButton jbtnNum12;
    private javax.swing.JButton jbtnNum13;
    private javax.swing.JButton jbtnNum14;
    private javax.swing.JButton jbtnNum15;
    private javax.swing.JButton jbtnNum16;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnQuit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSolve;
    private javax.swing.JLabel jlabaleClicksNumber;
    private javax.swing.JLabel jlabelClicks2;
    private javax.swing.JLabel jlabelClicks3;
    private javax.swing.JLabel jlabelClicks5;
    private javax.swing.JLabel jlabelClicks6;
    private javax.swing.JLabel jlabelClicks7;
    private javax.swing.JLabel jlabelTime;
    private javax.swing.JLabel jlabelusername;
    private javax.swing.JLabel jlblMin1;
    private javax.swing.JLabel jlblMin2;
    private javax.swing.JLabel jlblMoves1;
    private javax.swing.JLabel jlblMoves2;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel name1;
    // End of variables declaration                   
}
